apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: demo-ns
data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  nginx.conf: |
    worker_processes auto;
    events {
    }

    http {
      server {
        listen 80 ;
        location = /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
        location / {
          add_header Content-Type text/plain;
          return 200 'Hello World!!! <br/>';
        }
      }
    }
