apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: demo-ns
spec:
  tls:
    - hosts:
        - test.example
      secretName: test.example
  rules:
    - host: test.example
      http:
        paths:
          - backend:
              serviceName: nginx
              servicePort: 80
            path: /
