apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  namespace: demo-ns
spec:
  replicas: 10
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - kubia
                topologyKey: "kubernetes.io/hostname"
      containers:
        - image: luksa/kubia:v2
          name: nodejs
